apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    apps: webapps
  ports:
    - name: http
      port: 8080
      nodePort: 32000
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    apps: webapps
spec:
  containers:
  - name: pod1
    image: joerayan/myweb:0.0.3
    ports:
      - containerPort: 8080

testttt
add change
test addd change
